package com.gamingMatchMaker.gamingMatchMaker.Steam;

public class InvalidGameException extends Exception {

	/**
	 * auto-generated by eclipse
	 */
	private static final long serialVersionUID = -310287537546728985L;

	public InvalidGameException() {
		super();
	}

	public InvalidGameException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public InvalidGameException(String message, Throwable cause) {
		super(message, cause);
	}

	public InvalidGameException(String message) {
		super(message);
	}

	public InvalidGameException(Throwable cause) {
		super(cause);
	}

}
