package com.gamingMatchMaker.gamingMatchMaker.Steam;

public class InvalidGameException extends Exception {

	/**
<<<<<<< HEAD
<<<<<<< HEAD
	 * auto-generated by eclipse  
=======
	 * auto-generated by eclipse
>>>>>>> Initial files, and tweak to gitignore to not grab eclipse project file.
=======
	 * auto-generated by eclipse  
>>>>>>> fixing PEBKAC moment
	 */
	private static final long serialVersionUID = -310287537546728985L;

	public InvalidGameException() {
		super();
	}

	public InvalidGameException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public InvalidGameException(String message, Throwable cause) {
		super(message, cause);
	}

	public InvalidGameException(String message) {
		super(message);
	}

	public InvalidGameException(Throwable cause) {
		super(cause);
	}

}
