package com.gamingMatchMaker.gamingMatchMaker.Steam;

public class InvalidPlayerrException extends Exception {

	/**
	 * auto-generated by eclipse
	 */
	private static final long serialVersionUID = 2127770783034620060L;

	public InvalidPlayerrException() {
		super();
	}

	public InvalidPlayerrException(String arg0, Throwable arg1, boolean arg2, boolean arg3) {
		super(arg0, arg1, arg2, arg3);
	}

	public InvalidPlayerrException(String arg0, Throwable arg1) {
		super(arg0, arg1);
	}

	public InvalidPlayerrException(String arg0) {
		super(arg0);
	}

	public InvalidPlayerrException(Throwable arg0) {
		super(arg0);
	}

}
